### ISSUE TITLE
Student Summit Watch Party at Microsoft ADC Nigeria

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-tech-events#13]
[Here's the link. ](https://techcommunity.microsoft.com/t5/educator-developer-blog/student-summit-watch-party-at-microsoft-adc-nigeria/ba-p/3749855)

**Comment by Tonie-NG** [comment]
I think this event had been held already. You can go ahead and close the issue

**Comment by kaf-lamed-beyt** [comment]
Ah! Thanks for reminding me @Tonie-NG 🤲🏽
