### ISSUE TITLE
CCHub showcase event

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-tech-events#23]
CCHub is having an event this morning, by 11AM. Kindly update the readme with the link below 

[RSVP LINK](https://www.eventbrite.com/e/community-product-showcase-tickets-633271320567?ct=t(EMAIL_CAMPAIGN_5_31_2021_10_35_COPY_01)&mc_cid=1e81b3d071&mc_eid=1a92167282)

**Comment by kaf-lamed-beyt** [comment]
@Jemeni11 lemme know if you'd love to take this up

**Comment by kaf-lamed-beyt** [comment]
stale

**Comment by Jemeni11** [comment]
> CCHub is having an event this morning, by 11AM. Kindly update the readme with the link below
> 
> [RSVP LINK](https://www.eventbrite.com/e/community-product-showcase-tickets-633271320567?ct=t(EMAIL_CAMPAIGN_5_31_2021_10_35_COPY_01)&mc_cid=1e81b3d071&mc_eid=1a92167282)



> @Jemeni11 lemme know if you'd love to take this up

Me just seeing this now:
![Pokemon surprise face](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBJO3ApqGawYdNpKyEg5TUsZDIz5mLL9yIzd5B46XOHQ&s)

**Comment by kaf-lamed-beyt** [comment]
It was too sudden. I get 😃

You can try fixing the other issues

**Comment by Jemeni11** [comment]
Okay :+1: 

> It was too sudden. I get smiley
> 
> You can try fixing the other issues
