### ISSUE TITLE
Flow community Ilorin 

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-tech-events#24]
The Flow community in Ilorin is organizing their launch party

Kindly update the README with the [RSVP link](https://www.eventbrite.de/e/ilorin-flow-launch-party-tickets-634131413127), date, and other necessary information in the same format for the other events

**Comment by Jemeni11** [comment]
It's sold out. Should I still add it?

**Comment by kaf-lamed-beyt** [comment]
Let's add it. We'd probably just move it to "past events" in the future.

**Comment by dtechbro** [comment]
Hi there! I just read through the README file and I can see some of the events are passed already, Why aren't the event removed after it has taken place

**Comment by kaf-lamed-beyt** [comment]
We're hoping that this repo would be an archive of all events. Past, present, and future. 

So that people can be aware of these events and perhaps look forward to attending a particular event in the future (the next year, mostly).

**Comment by dtechbro** [comment]
Ok, I get that
