### ISSUE TITLE
We need a web user interface

### ISSUE THREAD

**Issue by Vida-TG** [kaf-lamed-beyt/ng-tech-events#29]
As events increase, it would be difficult to sort events, add events and see upcoming events, it would be better to have a web interface for the project

**Comment by kaf-lamed-beyt** [comment]
Yes. There's a design work of the UI going on... when it is live, I'll update the discussion section of this repo.

**Comment by Vida-TG** [comment]
Alright, can it be public so we can contribute too

**Comment by kaf-lamed-beyt** [comment]
That won't be an issue. I'll definitely do that. I'll also call your attention to it. 

But, you can also watch the discussions in this repo.

**Comment by Petsamuel** [comment]
I'm Also interested just incase.

**Comment by kaf-lamed-beyt** [comment]
No issue. I'll be back to this issue when we start.
