### ISSUE TITLE
Create JSON Format 

### ISSUE THREAD

**Issue by Petsamuel** [kaf-lamed-beyt/ng-tech-events#37]
Why JSON ?

JSON is a powerful and versatile format for storing data. It is easy to use, easy to parse, and easy to transmit. it's both human-readable and machine-readable, and can be used as an API

* **It's a lightweight Storge format.** 
* **It's versatile.**
* **It's portable.**

**Comment by kaf-lamed-beyt** [comment]
This is in the works already. Thanks for suggesting BTW! 🙌🏽🙌🏽💥

**Comment by Petsamuel** [comment]
Alright

**Comment by kaf-lamed-beyt** [comment]
fixed with this [commit](https://github.com/kaf-lamed-beyt/ng-tech-events/commit/218b15b3208648a3ec36c4b6b8b04d4159556f26)
