### ISSUE TITLE
invalid character under name row

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-tech-events#44]
When you look at the Ilorin category, there's a polygon event whose event title has an invalid character `[` You should remove it. 

Here's a Jumpstart on the exact line to focus on. 

https://github.com/kaf-lamed-beyt/ng-tech-events/blob/762ad240be4bf2bb0f0da251a1d67a6cceae76c2/README.md#L33

**Comment by Petsamuel** [comment]
oh that true

**Comment by kaf-lamed-beyt** [comment]
Yep. Thank for opening the PR, champ! 🚀
