### ISSUE TITLE
add event types

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-tech-events#45]
There's internal work going on with the public API of this repository that anyone can send a `GET` request to. 

There should be a way to categorize events based on their type. Say for example now, all events that fall under the **web3**, **design**, **IOT**, or **web** can be filtered and rendered as a list in the UI. 

What you'll be doing here is adding a new column to all the tables that'd accommodate this. For example, a `categories` title may suffice. But, feel free to call it whatever you want.

![image](https://github.com/kaf-lamed-beyt/ng-tech-events/assets/48127194/d52884d7-56c5-4315-ade6-18ce729085ac)

**Comment by kaf-lamed-beyt** [comment]
Yes, something like that.

**Comment by kaf-lamed-beyt** [comment]
@Petsamuel are you working on this? I need to know so I can assign you.

**Comment by Petsamuel** [comment]
yea

**Comment by kaf-lamed-beyt** [comment]
Oh, awesome! 

For events like these, should we place it under a "general" category?
