### ISSUE TITLE
SheCode Africa Summit 

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-tech-events#48]
Checkout the event details [here](http://summit.shecodeafrica.org/) 

Link to register is [here](https://tix.africa/discover/scasummit2)

Ensure you follow the exact date format that we're talking about in this issue 👉🏽 #47 

For context, this https://github.com/kaf-lamed-beyt/ng-tech-events/issues/47#issuecomment-1630738288 explains why you should adhere to the aforementioned date format.

**Comment by Tonie-NG** [comment]
I'm picking this up
