### ISSUE TITLE
Flutter Forward — ilorin 

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-tech-events#5]
[Here](https://gdg.community.dev/events/details/google-gdg-ilorin-presents-flutter-forward-extended-ilorin/)

**Comment by kaf-lamed-beyt** [comment]
@Jemeni11, if you're free, please add this to the list

**Comment by Jemeni11** [comment]
Hey
Thanks for assigning this to me.
I'm done with it :+1:

**Comment by kaf-lamed-beyt** [comment]
Ayy! It's nothing man! 

Thanks for contributing as always!
