### ISSUE TITLE
Google IO Extended Port Harcourt 2023

### ISSUE THREAD

**Issue by Tonie-NG** [kaf-lamed-beyt/ng-tech-events#57]
Event Details: [here](https://gdg.community.dev/events/details/google-gdg-port-harcourt-presents-google-io-extended-port-harcourt-2023/)

Registration link: [here (login to rsvp)](https://gdg.community.dev/accounts/login/?next=/events/details/google-gdg-port-harcourt-presents-google-io-extended-port-harcourt-2023/)

**Comment by Tonie-NG** [comment]
@kaf-lamed-beyt  I'm picking this up, kindly assign it to me

**Comment by kaf-lamed-beyt** [comment]
Ayy! I'm assigning you now.
