### ISSUE TITLE
create reusable `uniqueCategories` helper

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-tech-events#63]
Currently, the home page and the `<Categories />` component are using this variable &mdash; `uniqueCategories` in their modules here 👇🏼 

https://github.com/kaf-lamed-beyt/ng-tech-events/blob/9464eeddd307773c211cf1900eda74c210653ea6/frontend/src/containers/home/index.tsx#L27-L33

And here 👇🏼 

https://github.com/kaf-lamed-beyt/ng-tech-events/blob/9464eeddd307773c211cf1900eda74c210653ea6/frontend/src/components/categories/categories.tsx#L18-L24

It would be nice for us to have a module in [`src/utils`](https://github.com/kaf-lamed-beyt/ng-tech-events/tree/master/frontend/src/utils) that handles this for us. Providing a "write once, use everywhere" pattern for us.

**Comment by Tonie-NG** [comment]
Hello @kaf-lamed-beyt I'm interested in this. Kindly assign it to me

**Comment by kaf-lamed-beyt** [comment]
Ayy! I'll do that now.

Thank you so much, chief!

**Comment by Tonie-NG** [comment]
Okay, I've now set-up the project and I wanted to make a few comments before I proceed. First off, the `uniqueCategory` array should be a "global array" (this could morph into a database entity if we ever decide to swing that way). Now I can create a utility function that takes the `event` as a parameter and tries to modify/access the details of the `uniqueCategory` array. How do you see this?

**Comment by kaf-lamed-beyt** [comment]
Oh yes! This is exactly what we need to accomplish and this suggestion sounds good! 🚀

**Comment by kaf-lamed-beyt** [comment]
How's this coming @Tonie-NG?

**Comment by Tonie-NG** [comment]
@kaf-lamed-beyt it's coming along nicely. I've not had access to my laptop since day before yesterday. Going to pick it up this morning (it had some issues, hopefully it's been properly fixed now). Expect a PR by the end of today or tomorrow.

**Comment by kaf-lamed-beyt** [comment]
Dang! sorry about your PC.

I'll be looking forward to your PR

**Comment by Tonie-NG** [comment]
@kaf-lamed-beyt sensei, checkout my lastest pr
