### ISSUE TITLE
Web3 conference Lagos 

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-tech-events#68]
Web3bridge Africa is having a conference in Lagos 

Here's the [link](https://event.web3bridge.com/) for more information.

**Comment by Tonie-NG** [comment]
Hi @kaf-lamed-beyt I'm taking this up. Kindly assign it to me

**Comment by kaf-lamed-beyt** [comment]
Straight up!
