### ISSUE TITLE
GDG Lagos — IWD 

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-tech-events#7]
The event details is/are [here](https://gdg.community.dev/events/details/google-gdg-lagos-presents-international-womens-day-lagos/)

Kindly go through it and ask me to assign you to this issue, when you feel ready, and do not hesitate to ask me any question when you feel blocked. ✌🏽

**Comment by Tonie-NG** [comment]
If this issue is still unassigned, I'd like to take it up

**Comment by Tonie-NG** [comment]
@kaf-lamed-beyt

**Comment by kaf-lamed-beyt** [comment]
Ah, Yes! 

Give it a go. I'll assign you now. 🤞🏽

**Comment by Jemeni11** [comment]
Shouldn't this issue be closed?
I thought pull request #11 fixed this.

**Comment by kaf-lamed-beyt** [comment]
Dang!! I must have forgotten
