### ISSUE TITLE
Ethereum community meetup 9ja

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-tech-events#71]
## New Event

**Tell us a bit about the event.**

Welcome to an open Ethereum Community meetup!

​Come to connect with others from the Nigerian ecosystem and meet with leaders from Arbitrum, Scroll, ETHGlobal, and Etheruem community members.

**Share a link to the event below**

Here's the [link](https://lu.ma/9ie32ffq)

**What category does this event fall?**

web3

**Comment by PrimeFord** [comment]
done too

**Comment by kaf-lamed-beyt** [comment]
@Tonie-NG, is this PR (#78) related to this issue? 

So I can close it

**Comment by Tonie-NG** [comment]
No, it isn't. I can work on this if it's not taken

**Comment by kaf-lamed-beyt** [comment]
Alright, please do! 

It is not taken 🤲🏽

**Comment by kaf-lamed-beyt** [comment]
Ah! Shit! I forgot that @PrimeFord already worked in it before. 

But, he's yet to be back with any feedback from his PRs. ☹️

Try taking this up. And I'll inform him about it

**Comment by Tonie-NG** [comment]
Let's just wait for his feedback

**Comment by kaf-lamed-beyt** [comment]
Alright then. Thanks, chief!

**Comment by PrimeFord** [comment]
hey boss...
quickone should i just get rid of the commits first

**Comment by Tonie-NG** [comment]
@PrimeFord why? No longer working on it?

**Comment by kaf-lamed-beyt** [comment]
> hey boss... quickone should i just get rid of the commits first

Hi @PrimeFord, I think you should update your forked repo with this one so that all the latest changes are in sync. 

Then you can make your commits

**Comment by PrimeFord** [comment]
> 

ive done it already just remaining the PR

**Comment by kaf-lamed-beyt** [comment]
Awesome! 

I'll be looking forward to it, my chief! 🙌🏼

**Comment by PrimeFord** [comment]
![sync](https://github.com/kaf-lamed-beyt/ng-tech-events/assets/115805335/c6ac3407-9333-4ae0-9c38-9d525a299d90)
im still 26 commit ahead....

**Comment by PrimeFord** [comment]
28 sef

> ![sync](https://user-images.githubusercontent.com/115805335/258609495-c6ac3407-9333-4ae0-9c38-9d525a299d90.png) im still 26 commit ahead....

**Comment by kaf-lamed-beyt** [comment]
Dang! Try rebasing. 

First, make sure that you've commit your changes. 

```shell
git rebase master
```

**Comment by PrimeFord** [comment]
bruhhh i tried rebase buh the commit was just increasing.... i guess the mistake i made was that i was not suppose to commit to my master branch..... im suppose to be merging my master branh with yours after you merge a PR from me

**Comment by kaf-lamed-beyt** [comment]
Ah Dang!

**Comment by kaf-lamed-beyt** [comment]
One thing i do when it gets to this point is to delete my forked repo and try re-forking. 

Try this and let me know how it goes, would ya

**Comment by kaf-lamed-beyt** [comment]
Fixed via this [commit](https://github.com/kaf-lamed-beyt/ng-tech-events/commit/1de1fdb06bb39d44522b929daff8ed3e30aed6fd)
