### ISSUE TITLE
Keras Community Day Sub-Saharan Africa

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-tech-events#72]
**Tell us a bit about the event.**

Join  GDG Lagos & Google as we celebrate the power of Keras, foster connections within the ML community, and empower each other to create transformative solutions. Let's shape the future of AI together at Keras Community Day! 🌟 

**Share a link to the event below**

Here's the [link](https://www.meetup.com/gdg-lagos/events/295107621?response=3&action=rsvp&utm_medium=email&utm_source=braze_canvas&utm_campaign=mmrk_alleng_event_announcement_prod_v7_en&utm_term=promo&utm_content=lp_meetup)

**What category does this event fall?**

ML, AI, Online

**Comment by PrimeFord** [comment]
yes thats the category

**Comment by PrimeFord** [comment]
do you want me to come up with the API demo and also the table data in the ReadMe

**Comment by kaf-lamed-beyt** [comment]
I think you're commenting on a wrong a issue @PrimeFord

**Comment by PrimeFord** [comment]
i don't grab

**Comment by kaf-lamed-beyt** [comment]
Apologies! I thought you were referring to the search implementation issue. 

To attempt this issue, I don't think you need to come with an API demo, all you'd to do is just edit the table. 

In your case, it'll be the table in the online category.

**Comment by PrimeFord** [comment]
done boss

**Comment by kaf-lamed-beyt** [comment]
Fixed via this [commit](https://github.com/kaf-lamed-beyt/ng-tech-events/commit/1de1fdb06bb39d44522b929daff8ed3e30aed6fd)
