### ISSUE TITLE
Sec 101: Getting started with Cybersecurity 

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-tech-events#73]
**Tell us a bit about the event.**

Whether you're an aspiring security professional, a curious beginner, or a tech enthusiast looking to enhance your understanding of digital security, this event is tailor-made for you!

**Share a link to the event below**

Here's the [link to RSVP](https://gdg.community.dev/events/details/google-gdg-lagos-presents-sec-101-getting-started-with-cybersecurity/)

**What category does this event fall?**

Cybersecurity

**Comment by PrimeFord** [comment]
done

**Comment by kaf-lamed-beyt** [comment]
Fixed via this [commit](https://github.com/kaf-lamed-beyt/ng-tech-events/commit/1de1fdb06bb39d44522b929daff8ed3e30aed6fd)
