### ISSUE TITLE
new events 

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-tech-events#8]
Hi @Jemeni11,

Can you try taking a look at these events below, and see if you can filter the ones that may be happening in Nigeria?

[One](https://www.meetup.com/nginx-community-group-lagos-chapter/events/291357345/?utm_medium=email&utm_source=braze_canvas&utm_campaign=mmrk_alleng_event_announcement_prod_v7_en&utm_term=nurture&utm_content=lp_meetup), [two](https://www.meetup.com/africa-development-centre-adc-west-events-programs/events/291667187/?utm_medium=email&utm_source=braze_canvas&utm_campaign=mmrk_alleng_event_announcement_prod_v7_en&utm_term=nurture&utm_content=lp_meetup).

**Comment by Jemeni11** [comment]
The NGINX event is online but the group in charge of it is the NGINX Community Group: Lagos Chapter.
Do we need a new category or I should put it under lagos?

**Comment by Jemeni11** [comment]
I put it under lagos, if I need to change it, I will

**Comment by kaf-lamed-beyt** [comment]
I just dropped some comments [here](https://github.com/Jemeni11/ng-tech-events/commit/eb4a1ddaedb0fce308a0ce509ff819f8ea066e33#r102140341)

...about the online events. I think we should have a section for it at the top. Just like we do for the Cities. So we can have something like [Online]#online, such that when people click on it, they're scrolled down to that section. Makes sense?

**Comment by kaf-lamed-beyt** [comment]
fixes #9
