### ISSUE TITLE
DevFest Ibadan 2023 🛖🚗

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-tech-events#83]
**Tell us a bit about the event.**

DevFest Ibadan is an annual decentralized tech conference hosted by the Google Developer Groups (GDG) Ibadan. 

**Share a link to the event below**

[Here's the link
](https://gdg.community.dev/events/details/google-gdg-ibadan-presents-devfest-ibadan-2023/)

**What category does this event fall?**

Ai, career-development, web, general, design

**Comment by AbidemiT** [comment]
Nice, thanks for this.
What other detail would you like to make available concerning our upcoming DevFest Ibadan 2023?

Love what you're doing.

**Comment by kaf-lamed-beyt** [comment]
Thank you for the feedback @AbidemiT! 

I think the information above is quite okay. Unless there's more. I'd be delighted to have them. 

For now, we'd need someone to open a pull request that adds the event to our API and closes this issue.
