### ISSUE TITLE
DevFest Uyo 2023

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [kaf-lamed-beyt/ng-tech-events#88]
This is the [link to the event](https://gdg.community.dev/events/details/google-gdg-uyo-presents-devfest-uyo-2023/).

Please endeavor to include "devfest" as part of the category. Since this is a DevFest event.

**Comment by PrimeFord** [comment]
hi brother can i jump on this task

**Comment by kaf-lamed-beyt** [comment]
Hi Fuhad! Please do. 

It's nice to have you back! 🍾

**Comment by PrimeFord** [comment]
aiiit boss
thanks for having me

**Comment by PrimeFord** [comment]
Done chief....... buh the pull request failed some checks....
